name: botiga_biz
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.2+17

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  url_launcher: ^6.0.9
  provider: ^5.0.0
  package_info: ^2.0.2
  http: ^0.13.3
  json_annotation: ^4.0.1
  badges: ^2.0.1
  animations: ^2.0.1
  cached_network_image: ^3.1.0
  lottie: ^1.1.0
  share: ^2.0.4
  clipboard: ^0.1.2+5
  another_flushbar: ^1.10.24
  mask_text_input_formatter: ^2.0.0
  pin_code_fields: ^7.3.0
  flutter_secure_storage: ^4.2.0
  webview_flutter: ^2.0.10
  shared_preferences: ^2.0.6
  auto_size_text: ^2.1.0
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  flutter_cache_manager: ^3.1.2
  skeleton_text: ^3.0.0
  image_picker: ^0.6.7+14
  intro_slider: ^3.0.2
  app_settings: ^4.0.4
  image_cropper: ^1.3.1
  scrollable_positioned_list: ^0.1.8
  file_picker: ^2.1.5
  pdf_flutter: ^1.1.3

  # Firebase integration
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_analytics: ^8.2.0
  firebase_crashlytics: ^2.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.3
  json_serializable: ^4.1.1
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/launcher/launcher.png
  adaptive_icon_background: assets/launcher/background.png
  adaptive_icon_foreground: assets/launcher/foreground.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BotigaIcons
      fonts:
        - asset: assets/icons/BotigaIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
